### ISSUE TITLE
Argument at index 0 should not be empty?

### ISSUE THREAD

**Issue by mattRiddoch** [codediodeio/firestore-migrator#16]
The data was uploading fine a week ago? Not seeing anything empty missing in the spreadsheet?

See output below..
~~~~
Matthews-MacBook-Pro:firestore-migrator matt$ fire-migrate import --omit-empty-fields --dry-run homePageNewCats.xlsx homePageNewCats
Reading XLSX with options { sheet: '1', isColOriented: false, omitEmtpyFields: true }
XLSX read complete.
homePageNewCats/pmTrsnIgxgyx3mgNuacy
(node:68731) UnhandledPromiseRejectionWarning: Error: Argument at index 0 should not be empty.
    at new FieldPath (/Users/matt/Documents/GitHub/firestore-migrator/node_modules/@google-cloud/firestore/src/path.js:473:15)
    at Function.fromObject (/Users/matt/Documents/GitHub/firestore-migrator/node_modules/@google-cloud/firestore/src/document.js:1152:23)
    at WriteBatch.set (/Users/matt/Documents/GitHub/firestore-migrator/node_modules/@google-cloud/firestore/src/write-batch.js:292:41)
    at /Users/matt/Documents/GitHub/firestore-migrator/dist/importCollection/index.js:109:48
    at step (/Users/matt/Documents/GitHub/firestore-migrator/dist/importCollection/index.js:32:23)
    at Object.next (/Users/matt/Documents/GitHub/firestore-migrator/dist/importCollection/index.js:13:53)
    at /Users/matt/Documents/GitHub/firestore-migrator/dist/importCollection/index.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/matt/Documents/GitHub/firestore-migrator/dist/importCollection/index.js:3:12)
    at batchSet (/Users/matt/Documents/GitHub/firestore-migrator/dist/importCollection/index.js:101:12)
(node:68731) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:68731) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
~~~~

**Comment by stildalf** [comment]
Hi @mattRiddoch, the option `--omit-empty-fields` has been deprecated, it was provided by the now removed `xlsx-as-json` parser, which was changed to the `xlsx` package giving us import/export and multi-sheet abilities - amongst others.

Had you pulled and built from latest source, you'd have seen: `error: unknown option --omit-empty-fields`

It's worth recreating the same feature with the new parser, I'll have a look at that as soon as I can.

**Comment by mattRiddoch** [comment]
Ahhh ok much appreciated. Now this appears to be unrelated but after building from the latest I am still having issues? Here is what im seeing:
~~~
fire-migrate i -m test.simple.xlsx testing
Import success, Firestore updated!
Total documents: 0
~~~
This is being run from the samples directory. I get the same output running my xlsx examples. For whatever reason when I initially had some successful  imports from xlsx file the field type number vs string seemed to work fairly well (auto-detecting). I can successfully import from csv but it likes to make everything a string by default. I did see the option to set the type manually but I would like to avoid that for the time being if possible.
